- name: Ensure common tools are installed
  become: true
  ansible.builtin.package:
    name:
      - git
      - gpg
      - protobuf-compiler
      - stow
      - curl
      - golang
    state: present

- name: Install Specific Debian-based dependencies
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - libfuse-dev
    state: present

