---
- name: Ensure common directories are created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ local_app_dir }}"

- name: Set Profile session file for Debian-based systems
  set_fact:
    profile_session_file: ~/.profile
  when: ansible_facts['os_family'] == "Debian"

- name: Set Profile session file for RedHat-based systems
  set_fact:
    profile_session_file: ~/.bash_profile
  when: ansible_facts['os_family'] == "RedHat"

- name: Install common packages
  import_tasks: common.yml

- name: Install Rust dev environment
  import_tasks: rust.yml

- name: Install Java dev environment
  import_tasks: java.yml

- name: Install .NET dev environment
  import_tasks: dotnet.yml

- name: Install Go dev environment
  import_tasks: go.yml

- name: Install Lua dev environment
  import_tasks: lua.yml

- name: Install Neovim
  import_tasks: neovim.yml

- name: Install Docker
  import_tasks: docker.yml

- name: Make sure the local app directory is in PATH
  ansible.builtin.lineinfile:
    path: "{{ profile_session_file }}"
    line: "export PATH=$PATH:{{ local_app_dir }}"
    state: present
