---
- name: Ensure common directories are created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ local_app_dir }}"

- name: Install common packages
  import_tasks: common.yml

- name: Install Rust dev environment
  import_tasks: rust.yml

- name: Install Java dev environment
  import_tasks: java.yml

- name: Install .NET dev environment
  import_tasks: dotnet.yml

- name: Install Go dev environment
  import_tasks: go.yml

- name: Install Neovim
  import_tasks: neovim.yml

- name: Make sure the local app directory is in PATH
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: "export PATH=$PATH:{{ local_app_dir }}"
    state: present

