theme = "boo_berry"

[editor]
cursorline = true
idle-timeout = 0
color-modes = true
true-color = true
terminal.command = "gnome-terminal"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true