---
- name: Install automatic kmods tools for RedHat-based systems
  when: ansible_os_family == 'RedHat'
  become: true
  ansible.builtin.yum:
    name:
      - akmods
      - mokutil
      - kmodtool
      - openssl
    state: present

- name: Create a self generated key and certificate
  when: ansible_os_family == 'RedHat'
  become: true
  ansible.builtin.command:
    cmd: /usr/sbin/kmodgenca --auto

- name: Import self generated key
  when: ansible_os_family == 'RedHat'
  become: true
  ansible.builtin.command:
    cmd: mokutil --import /etc/pki/akmods/certs/public_key.der 
    stdin: "qwerty"

- name: Install Nvidia drivers
  when: ansible_os_family == 'RedHat'
  become: true
  ansible.builtin.yum:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - nvidia-vaapi-driver
      - libva-utils
      - vdpauinfo
    state: present
